apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-001-app
  labels:
    app: dp-001-app-dev
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: dp-001-app-dev
  template:
    metadata:
      labels:
        app: dp-001-app-dev
    spec:
      containers:
        - name: dp-001-app
          image: 381443105190.dkr.ecr.us-east-1.amazonaws.com/dp-001-app:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
