apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dp-001-app-dev
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: "dev-dp-001-app-alb"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:381443105190:certificate/8c7b8504-192e-41e4-8e4d-42e6f828e1c5
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/security-group-prefix-lists: pl-3b927c52
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: true
spec:
  ingressClassName: alb
  rules:
    - host: dp-001.dev.lmv-dev.top
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: dp-001-app
                port:
                  number: 3000
